const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "Trending",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "Iconic Cities",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "Mountains",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "Castles",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "Camping",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "Amazing Pools",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "Farms",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "Rooms",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: "Arctic",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "Farms",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Relax in this quintessential English cottage with picturesque gardens and cozy interiors.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1472220625704-91e1462799b2?ixlib=rb-4.0.3",
    },
    price: 1100,
    location: "Cotswolds",
    country: "United Kingdom",
    category: "Domes",
  },
  {
    title: "Overwater Bungalow in Bora Bora",
    description: "Experience luxury and romance in an overwater bungalow with direct access to the crystal-clear lagoon.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?ixlib=rb-4.0.3",
    },
    price: 5000,
    location: "Bora Bora",
    country: "French Polynesia",
    category: "Boats",
  },
  {
    title: "Desert Oasis Retreat",
    description: "Escape to a tranquil desert retreat with a private pool and stunning views of the dunes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505692794403-34d4982d6edc?ixlib=rb-4.0.3",
    },
    price: 1800,
    location: "Palm Springs",
    country: "United States",
    category: "Trending",
  },
  {
    title: "Japanese Ryokan Experience",
    description: "Immerse yourself in Japanese culture with a stay in a traditional ryokan featuring tatami mats and hot springs.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1559582930-efb20e03f8a0?ixlib=rb-4.0.3",
    },
    price: 2200,
    location: "Kyoto",
    country: "Japan",
    category: "Rooms",
  },
  {
    title: "Private Island Getaway",
    description: "Have an entire island to yourself with luxurious amenities and pristine beaches.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?ixlib=rb-4.0.3",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "Iconic Cities",
  },
  {
    title: "Countryside Farmhouse",
    description: "Experience rural life in this charming farmhouse surrounded by fields and fresh air.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?ixlib=rb-4.0.3",
    },
    price: 700,
    location: "Normandy",
    country: "France",
    category: "Farms",
  },
  {
    title: "Igloo Stay under Northern Lights",
    description: "Sleep under the stars and watch the Northern Lights from the comfort of a glass igloo.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?ixlib=rb-4.0.3",
    },
    price: 3200,
    location: "Lapland",
    country: "Finland",
    category: "Arctic",
  },
  {
    title: "Castle in the Scottish Highlands",
    description: "Live like royalty in a historic castle surrounded by misty mountains and lochs.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?ixlib=rb-4.0.3",
    },
    price: 4500,
    location: "Inverness",
    country: "Scotland",
    category: "Castles",
  },
  {
    title: "Houseboat Adventure",
    description: "Sail and sleep on a traditional houseboat with modern comforts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3",
    },
    price: 2500,
    location: "Kerala",
    country: "India",
    category: "Boats",
  },
  {
    title: "Modern Desert Dome",
    description: "Stay in a stylish dome home in the desert with stargazing opportunities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542317854-f9596ae57084?ixlib=rb-4.0.3",
    },
    price: 1400,
    location: "Joshua Tree",
    country: "United States",
    category: "Domes",
  },
  {
    title: "Glacier Ice Hotel",
    description: "Spend the night in an ice-carved hotel with unique sculptures and chilly charm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519817650390-64a93db511aa?ixlib=rb-4.0.3",
    },
    price: 2800,
    location: "Jukkasjärvi",
    country: "Sweden",
    category: "Arctic",
  },
  {
    title: "Camping by the River",
    description: "Pitch your tent right by the riverbank and enjoy fishing and bonfires.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3",
    },
    price: 500,
    location: "Rishikesh",
    country: "India",
    category: "Camping",
  },
  {
    title: "Greek Cliffside Villa",
    description: "Enjoy breathtaking ocean views from a villa perched on Santorini’s cliffs.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3",
    },
    price: 3800,
    location: "Santorini",
    country: "Greece",
    category: "Iconic Cities",
  },
  {
    title: "Luxury Floating Resort",
    description: "Stay in a floating villa surrounded by turquoise waters and marine life.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3",
    },
    price: 4500,
    location: "Maldives",
    country: "Maldives",
    category: "Boats",
  },
  {
    title: "Swiss Mountain Lodge",
    description: "A cozy alpine lodge surrounded by snowy peaks.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519821172141-b5d8f16dfc83?ixlib=rb-4.0.3",
    },
    price: 3200,
    location: "Zermatt",
    country: "Switzerland",
    category: "Mountains",
  },
  {
    title: "Rainforest Retreat",
    description: "Stay deep in the rainforest with exotic wildlife all around.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?ixlib=rb-4.0.3",
    },
    price: 1700,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "Trending",
  },
  {
    title: "Palace Stay in Rajasthan",
    description: "Live like royalty in a Rajasthani palace with grandeur and heritage charm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500048993959-d5f6e9c5f5a0?ixlib=rb-4.0.3",
    },
    price: 5000,
    location: "Jaipur",
    country: "India",
    category: "Castles",
  },
  {
    title: "Luxury Pool Villa",
    description: "Relax in a villa with a private infinity pool overlooking the hills.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?ixlib=rb-4.0.3",
    },
    price: 4200,
    location: "Phuket",
    country: "Thailand",
    category: "Amazing Pools",
  },
  {
    title: "Cozy Mountain Hut",
    description: "A tiny hut high in the Himalayas with unbeatable sunrise views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad1?ixlib=rb-4.0.3",
    },
    price: 900,
    location: "Manali",
    country: "India",
    category: "Mountains",
  },
  {
    title: "myNewWallpaper",
    description: "This is trial and next after adding category section",
    image: {
      filename: "wanderlust_DEV/am6nzcumexuf0zqboqyd",
      url: "https://res.cloudinary.com/dvjvgikfa/image/upload/v1757942741/wanderlust_DEV/am6nzcumexuf0zqboqyd.jpg",
    },
    price: 454,
    location: "Chandrapur",
    country: "India",
    category: "Farms",
  },
];

module.exports = { data: sampleListings };
